
-- oracle
CREATE TABLE TABLE_SYNC_CONFIG (	
	SRC_DS_NAME VARCHAR2(200) NOT NULL, 
	DEST_DS_NAME VARCHAR2(200) NOT NULL, 
	SYNC_TYPE VARCHAR2(200), 
	SRC_TABLE VARCHAR2(200), 
	SRC_SQL VARCHAR2(4000), 
	DEST_TABLE VARCHAR2(200) NOT NULL, 
	PK_NAMES VARCHAR2(2000), 
	UPDATE_WHERE_SQL VARCHAR2(4000), 
	UPDATE_WHERE_COLS VARCHAR2(2000), 
	OPER_TIME DATE DEFAULT SYSDATE, 
	VALID CHAR(1) DEFAULT '1' NOT NULL, 
	UUID VARCHAR2(32) DEFAULT SYS_GUID() NOT NULL, 
	CONSTRAINT TABLE_SYNC_CONFIG_PK PRIMARY KEY (UUID)
);

-- mysql
CREATE TABLE TABLE_SYNC_CONFIG (	
	SRC_DS_NAME VARCHAR(200) NOT NULL, 
	DEST_DS_NAME VARCHAR(200) NOT NULL, 
	SYNC_TYPE VARCHAR(200), 
	SRC_TABLE VARCHAR(200), 
	SRC_SQL VARCHAR(4000), 
	DEST_TABLE VARCHAR(200) NOT NULL, 
	PK_NAMES VARCHAR(2000), 
	UPDATE_WHERE_SQL VARCHAR(4000), 
	UPDATE_WHERE_COLS VARCHAR(2000), 
	OPER_TIME timestamp DEFAULT CURRENT_TIMESTAMP, 
	VALID CHAR(1) DEFAULT '1' , 
	UUID VARCHAR(36) PRIMARY KEY
);

