create or replace TRIGGER #TRIGGER_NAME# 
BEFORE DELETE OR UPDATE ON #TABLE_NAME# FOR EACH ROW
DECLARE
	OPER_TYPE CHAR(1);
BEGIN
  IF DELETING THEN
    OPER_TYPE:='D';
  END IF;
  IF UPDATING THEN
    OPER_TYPE:='U';
  END IF;
  INSERT INTO #TABLE_NAME#_HIS(
		#COLUMNS#
	    OPER_DATE_,
	    OPER_TYPE_
	  )values(
		#OLD_COLUMNS#
	    SYSDATE,
	    OPER_TYPE
	  );
END;
/